### ISSUE TITLE
Playing on a small window size

### ISSUE THREAD

**Issue by pphlek** [ketanhwr/reflexio#40]
If you try loading the game when the browser is small enough, the ratio sizes of the visuals don't change so everything gets bunched up together. The asteroids will get bunched up together to the point where it's impossible to win the game.

**Comment by ketanhwr** [comment]
A Screenshot?

**Comment by pphlek** [comment]
![screen shot 2018-01-18 at 8 59 19 am](https://user-images.githubusercontent.com/7154035/35101557-0006f784-fc2e-11e7-8aae-2dd389ee7754.png)

**Comment by ketanhwr** [comment]
Well, I don't think this is a bug. Obviously if you play in a small screen, such things would hapen.
